final_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"

trajectory_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"

trajectory_planner2:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"

trajectory_planner3:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"

trajectory_follower:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"

trajectory_follower2:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"

trajectory_follower_uturn:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"
